In [2]:

import networkx as nx
H = nx.read_gml('/Users/clipo/Documents/PycharmProjects/RapaNuiSim/testdata/island_test.gml')
nx.info(H)

import numpy as np
# get the column totals
g_mat = nx.to_numpy_matrix(H).astype(np.float)

print ("g_mat", g_mat)
rtot = np.sum(g_mat, axis = 0)
scaled = (g_mat / rtot) * 0.02
diag = np.eye(np.shape(g_mat)[0]) * (1.0 - 0.02)
g_mat_scaled = diag + scaled
print("scaled migration matrix: %s", g_mat_scaled.tolist())


g_mat [[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  1.  1.  1.  0.]]


/Users/clipo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


scaled migration matrix: %s [[0.98, 0.0, 0.0, 0.0, nan], [0.005, 0.98, 0.0, 0.0, nan], [0.005, 0.006666666666666666, 0.98, 0.0, nan], [0.005, 0.006666666666666666, 0.01, 0.98, nan], [0.005, 0.006666666666666666, 0.01, 0.02, nan]]
